version: "3.5"

services:

  standards-lab-web:
    environment:
      DEBUG: 'True'
    volumes:
      - "./:/code"
    command: "sh -c 'mkdir -p /code/projects_dir/ && cd standards_lab && gunicorn --reload --bind 0.0.0.0:80 wsgi:application '"

  standards-lab-worker:
    environment:
      DEBUG: 'True'
    volumes:
      - "./:/code"

