version: "3.5"

services:

  standards-lab-web:
    build: .
    ports:
      - "8000:80"
    environment:
      REDIS_URL: "redis://redis:6379"
      ROOT_PROJECTS_DIR: /code/projects_dir/
    volumes:
      - "./projects_dir:/projects_dir"

  standards-lab-worker:
    build: .
    environment:
      REDIS_URL: "redis://redis:6379"
      ROOT_PROJECTS_DIR: /code/projects_dir/
    volumes:
      - "./projects_dir:/projects_dir"
    command: "sh -c 'cd standards_lab && python manage.py rqworker default'"

  redis:
    image: redis:6.0.10
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./_build/redis-data:/data
